export const ERROR_CODES = {
  USERNAME_ALREADY_EXISTS: 'USERNAME_ALREADY_EXISTS',
  NICKNAME_ALREADY_EXISTS: 'NICKNAME_ALREADY_EXISTS',
} as const;

export const LOCAL_ERROR_CODES = {
  INVALID_CREDENTIALS: 'INVALID_CREDENTIALS',
} as const;

export const ACCESS_TOKEN_ERROR_CODES = {
  EXPIRED_ACCESS_TOKEN: 'EXPIRED_ACCESS_TOKEN',
  ACCESS_TOKEN_MISSING: 'ACCESS_TOKEN_MISSING',
  INVALID_ACCESS_TOKEN: 'INVALID_ACCESS_TOKEN',
} as const;

export const REFRESH_TOKEN_ERROR_CODES = {
  EXPIRED_REFRESH_TOKEN: 'EXPIRED_REFRESH_TOKEN',
  REFRESH_TOKEN_MISSING: 'REFRESH_TOKEN_MISSING',
  REFRESH_TOKEN_NOT_FOUND: 'REFRESH_TOKEN_NOT_FOUND',
  INVALID_REFRESH_TOKEN: 'INVALID_REFRESH_TOKEN',
} as const;
