export const USER_ERROR_CODES = {
  USERNAME_ALREADY_EXISTS: 'USERNAME_ALREADY_EXISTS',
  NICKNAME_ALREADY_EXISTS: 'NICKNAME_ALREADY_EXISTS',
} as const;

export const AUTH_ERROR_CODES = {
  INVALID_CREDENTIALS: 'INVALID_CREDENTIALS',
} as const;

export const ACCESS_TOKEN_ERROR_CODES = {
  EXPIRED_ACCESS_TOKEN: 'EXPIRED_ACCESS_TOKEN',
  ACCESS_TOKEN_MISSING: 'ACCESS_TOKEN_MISSING',
  INVALID_ACCESS_TOKEN: 'INVALID_ACCESS_TOKEN',
} as const;

export const REFRESH_TOKEN_ERROR_CODES = {
  EXPIRED_REFRESH_TOKEN: 'EXPIRED_REFRESH_TOKEN',
  REFRESH_TOKEN_MISSING: 'REFRESH_TOKEN_MISSING',
  REFRESH_TOKEN_NOT_FOUND: 'REFRESH_TOKEN_NOT_FOUND',
  INVALID_REFRESH_TOKEN: 'INVALID_REFRESH_TOKEN',
} as const;

export const AUTH_DOMAIN_ERRORS: Record<string, { field: string; reason: string }> = {
  USERNAME_ALREADY_EXISTS: {
    field: 'username',
    reason: 'This username is already in use',
  },
  NICKNAME_ALREADY_EXISTS: {
    field: 'nickname',
    reason: 'This nickname is already in use',
  },
};
