export const GAME_ERRORS = {
  PHASE_MUST_BE_LOADING: 'GAME_PHASE_MUST_BE_LOADING',
  PHASE_MUST_BE_THEME_SELECTING: 'GAME_PHASE_MUST_BE_THEME_SELECTING',
  CONTEXT_INVALID: 'GAME_CONTEXT_INVALID',
  PERMISSION_DENIED_SELECTOR: 'GAME_PERMISSION_DENIED_SELECTOR',
  THEME_INVALID: 'GAME_THEME_INVALID',
  THEME_NOT_SET: 'GAME_THEME_NOT_SET',
} as const;

export const GAME_EVENTS = {
  LOADING_STARTED: 'game.loading.started',
} as const;
